# ClearLagg configuration file

# Please not edit config version
config-version: 2

# Time in seconds between automatic clears
auto-clear-interval: 300

# World-specific settings
worlds:
  world:
    enable-auto-clear: true
  world_nether:
    enable-auto-clear: true
  world_the_end:
    enable-auto-clear: true

# Player notifications
notify-players:
  enable: true
  message: "§l§e•§f Tất cả vật phẩm trên mặt đất sẽ bị thổi bay sau 5 phút nữa, hãy dọn đồ!"
  countdown: 300
